# Generated by Django 4.1.1 on 2022-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xona1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('o_narx', models.IntegerField()),
                ('y_narx', models.IntegerField()),
                ('rasim', models.ImageField(upload_to='media')),
                ('soni1', models.IntegerField()),
                ('soni2', models.IntegerField()),
                ('manzil', models.CharField(max_length=100)),
                ('kv', models.FloatField()),
                ('kun', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
