# Generated by Django 4.1.2 on 2022-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_happyclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasim', models.ImageField(upload_to='media')),
                ('ism', models.CharField(max_length=20)),
                ('lavozim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('kun', models.DateTimeField(auto_now=True)),
                ('rasim', models.ImageField(upload_to='media')),
                ('malumot', models.CharField(max_length=100)),
            ],
        ),
    ]
