# Generated by Django 4.0.4 on 2022-10-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Murojat',
        ),
    ]
