# Generated by Django 4.1.2 on 2022-10-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_contact_murojat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xona1',
            old_name='o_narx',
            new_name='onarx',
        ),
        migrations.RenameField(
            model_name='xona1',
            old_name='y_narx',
            new_name='ynarx',
        ),
    ]
