# Generated by Django 4.1.2 on 2022-10-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_rename_o_narx_xona1_onarx_rename_y_narx_xona1_ynarx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xona1',
            old_name='onarx',
            new_name='olnarx',
        ),
        migrations.RenameField(
            model_name='xona1',
            old_name='ynarx',
            new_name='yanginarx',
        ),
    ]
