# Generated by Django 4.1.2 on 2022-10-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_rename_onarx_xona1_olnarx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xona1',
            old_name='olnarx',
            new_name='o_narx',
        ),
        migrations.RenameField(
            model_name='xona1',
            old_name='yanginarx',
            new_name='y_narx',
        ),
    ]
